# The containers that compose the project
services:
  db:
    image: postgres:17
    restart: always
    container_name: postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
